#include "opengenesis/config/toml_config.hpp"
#include "opengenesis/core/region_registry.hpp"
#include "opengenesis/core/world_registry.hpp"
#include "opengenesis/physics/physics_world.hpp"
#include "opengenesis/protocol/frame.hpp"
#include "opengenesis/world/region_runtime.hpp"
#include <chrono>
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <thread>
namespace {void expect(bool c,const char*m){if(!c)throw std::runtime_error(m);}void config_test(){const auto c=opengenesis::config::TomlConfig::parse("[a]\nx=42\ny=2.5\nz=true\n");expect(c.get_int("a.x")==42,"config int");expect(c.get_double("a.y")==2.5,"config double");expect(c.get_bool("a.z"),"config bool");}void frame_test(){opengenesis::protocol::Frame f{opengenesis::protocol::MessageType::region_metrics,7,opengenesis::protocol::payload_from_string("x=1\n")};const auto d=opengenesis::protocol::decode(opengenesis::protocol::encode(f));expect(d.type==f.type&&d.request_id==7,"frame roundtrip");}void registry_test(){const auto dir=std::filesystem::temp_directory_path()/"ogl-tests";std::filesystem::create_directories(dir);const auto wp=(dir/"worlds.db").string(),rp=(dir/"regions.db").string();std::filesystem::remove(wp);std::filesystem::remove(rp);opengenesis::core::WorldRegistry w(wp);const auto n=w.register_or_reconnect("w1","World","127.0.0.1:1");expect(n.generation==1,"generation 1");const auto n2=w.register_or_reconnect("w1","World","127.0.0.1:1");expect(n2.generation==2,"generation 2");opengenesis::core::RegionRegistry r(rp);std::string reason;expect(r.register_region({.id="r1",.name="Region",.node_id="w1",.grid_x=1,.grid_y=1,.node_generation=2},reason),"region register");expect(r.update_state("r1","w1",2,"starting",reason),"region starting");expect(r.update_state("r1","w1",2,"online",reason),"region online");expect(!r.register_region({.id="r2",.name="Other",.node_id="w1",.grid_x=1,.grid_y=1,.node_generation=2},reason),"collision reject");}void physics_test(){opengenesis::physics::PhysicsWorld p;const auto id=p.add_body({.position={0,0,10},.velocity={0,0,0},.mass=1});p.step(0.1);expect(p.body(id).position.z<10,"gravity integration");for(int i=0;i<200;++i)p.step(0.05);expect(p.body(id).position.z>=0,"ground contact");}void runtime_test(){opengenesis::world::RegionRuntime r("test",60);r.spawn_entity("avatar",true,true);r.start();std::this_thread::sleep_for(std::chrono::milliseconds{120});r.stop();const auto m=r.metrics();expect(m.ticks>2,"runtime ticks");expect(m.entities==1&&m.avatars==1&&m.physics_bodies==1,"runtime metrics");}}
int main(){try{config_test();frame_test();registry_test();physics_test();runtime_test();std::cout<<"OpenGenesisLINK 0.2.0 foundation tests: PASS\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
