#include "opengenesis/common/log.hpp"
#include "opengenesis/config/toml_config.hpp"
#include "opengenesis/network/tcp.hpp"
#include "opengenesis/protocol/frame.hpp"
#include "opengenesis/world/region_runtime.hpp"
#include <atomic>
#include <chrono>
#include <csignal>
#include <iomanip>
#include <memory>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
using opengenesis::common::LogLevel;namespace protocol=opengenesis::protocol;
namespace {std::atomic_bool running{true};void sig(int){running=false;}std::pair<std::string,std::uint16_t> endpoint(const std::string&e){const auto s=e.rfind(':');if(s==std::string::npos)throw std::runtime_error("endpoint must be host:port");return{e.substr(0,s),static_cast<std::uint16_t>(std::stoul(e.substr(s+1)))};}std::string field(const std::string&p,const std::string&k){std::istringstream in(p);std::string l;while(std::getline(in,l)){const auto s=l.find('=');if(s!=std::string::npos&&l.substr(0,s)==k)return l.substr(s+1);}return{};}struct RegionCfg{std::string id,name;int x,y;};}
int main(int argc,char**argv){std::signal(SIGINT,sig);std::signal(SIGTERM,sig);try{const auto cfg=opengenesis::config::TomlConfig::load_file(argc>1?argv[1]:"config/world.toml");const auto node_id=cfg.get_string("node.id","world-01"),node_name=cfg.get_string("node.name","World Node 01"),public_ep=cfg.get_string("network.public_endpoint","127.0.0.1:19100");const auto [host,port]=endpoint(cfg.get_string("core.endpoint","127.0.0.1:19000"));const auto reconnect=std::chrono::seconds{cfg.get_int("core.reconnect_seconds",2)};const auto lease=std::chrono::seconds{cfg.get_int("core.lease_seconds",5)};const auto hz=cfg.get_double("runtime.tick_hz",45.0);const int count=static_cast<int>(cfg.get_int("regions.count",1));std::vector<RegionCfg> rc;for(int i=0;i<count;++i){const auto p="region"+std::to_string(i)+".";rc.push_back({cfg.get_string(p+"id","region-"+std::to_string(i+1)),cfg.get_string(p+"name","Region "+std::to_string(i+1)),static_cast<int>(cfg.get_int(p+"grid_x",1000+i)),static_cast<int>(cfg.get_int(p+"grid_y",1000))});}
while(running){try{opengenesis::common::log(LogLevel::info,"world","Connecting to core "+host+":"+std::to_string(port));auto socket=opengenesis::network::TcpSocket::connect(host,port);std::uint32_t req=1;socket.send_frame({protocol::MessageType::hello,req,protocol::payload_from_string("client=opengenesis-world\nprotocol=1\n")});if(socket.receive_frame().type!=protocol::MessageType::hello_ack)throw std::runtime_error("HELLO rejected");std::ostringstream reg;reg<<"id="<<node_id<<"\nname="<<node_name<<"\nendpoint="<<public_ep<<"\n";socket.send_frame({protocol::MessageType::world_register,++req,protocol::payload_from_string(reg.str())});const auto ack=socket.receive_frame();if(ack.type!=protocol::MessageType::world_register_ack)throw std::runtime_error("world registration rejected");const auto generation=std::stoull(field(protocol::payload_as_string(ack),"generation"));opengenesis::common::log(LogLevel::info,"world","Connected generation "+std::to_string(generation));std::vector<std::unique_ptr<opengenesis::world::RegionRuntime>> runtimes;for(const auto&r:rc){std::ostringstream body;body<<"id="<<r.id<<"\nname="<<r.name<<"\ngrid_x="<<r.x<<"\ngrid_y="<<r.y<<"\n";socket.send_frame({protocol::MessageType::region_register,++req,protocol::payload_from_string(body.str())});if(socket.receive_frame().type!=protocol::MessageType::region_register_ack)throw std::runtime_error("region registration rejected: "+r.id);auto rt=std::make_unique<opengenesis::world::RegionRuntime>(r.id,hz);rt->spawn_entity("Foundation Object",false,true);rt->spawn_entity("Foundation Avatar",true,true);rt->start();for(const char* state:{"starting","online"}){socket.send_frame({protocol::MessageType::region_state_update,++req,protocol::payload_from_string("id="+r.id+"\nstate="+state+"\n")});if(socket.receive_frame().type!=protocol::MessageType::region_state_ack)throw std::runtime_error("region state rejected");}runtimes.push_back(std::move(rt));}
auto next_lease=std::chrono::steady_clock::now();auto next_metrics=next_lease;while(running){const auto now=std::chrono::steady_clock::now();if(now>=next_lease){socket.send_frame({protocol::MessageType::world_lease,++req,protocol::payload_from_string("node="+node_id+"\ngeneration="+std::to_string(generation)+"\n")});if(socket.receive_frame().type!=protocol::MessageType::world_lease_ack)throw std::runtime_error("lease rejected");next_lease=now+lease;}if(now>=next_metrics){for(const auto&rt:runtimes){const auto m=rt->metrics();std::ostringstream b;b<<std::fixed<<std::setprecision(2)<<"id="<<rt->id()<<"\nticks="<<m.ticks<<"\nentities="<<m.entities<<"\navatars="<<m.avatars<<"\nphysics_bodies="<<m.physics_bodies<<"\nsim_fps="<<m.sim_fps<<"\n";socket.send_frame({protocol::MessageType::region_metrics,++req,protocol::payload_from_string(b.str())});if(socket.receive_frame().type!=protocol::MessageType::region_metrics_ack)throw std::runtime_error("metrics rejected");}next_metrics=now+std::chrono::seconds{2};}std::this_thread::sleep_for(std::chrono::milliseconds{100});}
for(std::size_t i=0;i<runtimes.size();++i){for(const char* state:{"stopping","offline"}){socket.send_frame({protocol::MessageType::region_state_update,++req,protocol::payload_from_string("id="+rc[i].id+"\nstate="+state+"\n")});(void)socket.receive_frame();}runtimes[i]->stop();}socket.send_frame({protocol::MessageType::goodbye,++req,{}});return 0;}catch(const std::exception&e){if(!running)break;opengenesis::common::log(LogLevel::warning,"world.reconnect",e.what());std::this_thread::sleep_for(reconnect);}}
return 0;}catch(const std::exception&e){opengenesis::common::log(LogLevel::error,"world",e.what());return 1;}}
