#include "opengenesis/core/asset_store.hpp"
#include "opengenesis/platform/filesystem.hpp"
#include "opengenesis/security/crypto.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <vector>
namespace opengenesis::core { namespace {
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
std::string hex(std::string_view v){constexpr char h[]="0123456789abcdef";std::string o(v.size()*2,'0');for(size_t i=0;i<v.size();++i){auto c=(unsigned char)v[i];o[i*2]=h[c>>4];o[i*2+1]=h[c&15];}return o;}
unsigned char nib(char c){if(c>='0'&&c<='9')return static_cast<unsigned char>(c-'0');if(c>='a'&&c<='f')return static_cast<unsigned char>(c-'a'+10);if(c>='A'&&c<='F')return static_cast<unsigned char>(c-'A'+10);throw std::runtime_error("hex");}
std::string unhex(std::string_view v){if(v.size()%2)throw std::runtime_error("hex");std::string o(v.size()/2,'\0');for(size_t i=0;i<o.size();++i)o[i]=(char)((nib(v[i*2])<<4)|nib(v[i*2+1]));return o;}
std::vector<std::string> tabs(const std::string& l){std::vector<std::string>f;size_t s=0;for(;;){auto e=l.find('\t',s);f.push_back(l.substr(s,e==std::string::npos?e:e-s));if(e==std::string::npos)break;s=e+1;}return f;}
bool valid_text(std::string_view v,std::size_t max){return !v.empty()&&v.size()<=max&&std::none_of(v.begin(),v.end(),[](unsigned char c){return c<0x20||c==0x7f;});}
}
AssetStore::AssetStore(std::string metadata,std::filesystem::path blobs,std::size_t max):metadata_path_(std::move(metadata)),blob_directory_(std::move(blobs)),max_asset_bytes_(max){load();}
std::optional<AssetInfo> AssetStore::create(std::string owner,std::string name,std::string mime,std::string data,std::string& reason,PermissionMask perms,PermissionMask next){if(owner.empty()||!valid_text(name,128)||!valid_text(mime,128)||data.empty()||data.size()>max_asset_bytes_){reason="invalid-asset";return std::nullopt;}perms&=perm_all;next&=perms;const auto hash=security::sha256_hex(data);std::filesystem::create_directories(blob_directory_);const auto blob=blob_directory_/hash;if(!std::filesystem::exists(blob)){std::ofstream out(blob,std::ios::binary|std::ios::trunc);if(!out){reason="asset-storage-failed";return std::nullopt;}out.write(data.data(),static_cast<std::streamsize>(data.size()));}AssetInfo a{.id=security::random_hex(16),.owner_user_id=std::move(owner),.name=std::move(name),.mime_type=std::move(mime),.content_hash=hash,.size=data.size(),.permissions=perms,.next_owner_permissions=next,.created_unix=now()};std::scoped_lock l(mutex_);assets_[a.id]=a;persist_locked();reason.clear();return a;}
std::optional<AssetInfo> AssetStore::transfer(std::string_view id,std::string_view from,std::string to,bool keep,std::string& reason){if(to.empty()||to==from){reason="invalid-recipient";return std::nullopt;}std::scoped_lock l(mutex_);auto it=assets_.find(std::string{id});if(it==assets_.end()||it->second.owner_user_id!=from){reason="asset-not-owned";return std::nullopt;}if(!has_permission(it->second.permissions,perm_transfer)){reason="transfer-not-permitted";return std::nullopt;}if(keep&&!has_permission(it->second.permissions,perm_copy)){reason="copy-not-permitted";return std::nullopt;}AssetInfo result=it->second;result.owner_user_id=std::move(to);result.permissions=it->second.next_owner_permissions;result.next_owner_permissions&=result.permissions;result.created_unix=now();if(keep){result.id=security::random_hex(16);assets_[result.id]=result;}else{it->second=result;}persist_locked();reason.clear();return result;}
std::optional<AssetInfo> AssetStore::find(std::string_view id)const{std::scoped_lock l(mutex_);auto it=assets_.find(std::string{id});return it==assets_.end()?std::nullopt:std::optional<AssetInfo>{it->second};}
std::optional<std::string> AssetStore::read(std::string_view id,std::string_view owner)const{std::string hash;{std::scoped_lock l(mutex_);auto it=assets_.find(std::string{id});if(it==assets_.end()||it->second.owner_user_id!=owner)return std::nullopt;hash=it->second.content_hash;}std::ifstream in(blob_directory_/hash,std::ios::binary);if(!in)return std::nullopt;return std::string((std::istreambuf_iterator<char>(in)),{});}
std::vector<AssetInfo> AssetStore::list_for_user(std::string_view u)const{std::scoped_lock l(mutex_);std::vector<AssetInfo>r;for(auto&[_,a]:assets_)if(a.owner_user_id==u)r.push_back(a);std::sort(r.begin(),r.end(),[](auto&a,auto&b){return a.created_unix<b.created_unix;});return r;}
std::vector<AssetInfo> AssetStore::list_all()const{std::scoped_lock l(mutex_);std::vector<AssetInfo>r;r.reserve(assets_.size());for(auto&[_,a]:assets_)r.push_back(a);std::sort(r.begin(),r.end(),[](auto&a,auto&b){return a.created_unix<b.created_unix;});return r;}
std::optional<std::string> AssetStore::read_exportable(std::string_view id)const{std::string hash;{std::scoped_lock l(mutex_);auto it=assets_.find(std::string{id});if(it==assets_.end()||!has_permission(it->second.permissions,perm_export))return std::nullopt;hash=it->second.content_hash;}std::ifstream in(blob_directory_/hash,std::ios::binary);if(!in)return std::nullopt;return std::string((std::istreambuf_iterator<char>(in)),{});}
std::size_t AssetStore::count()const{std::scoped_lock l(mutex_);return assets_.size();}
std::uint64_t AssetStore::total_bytes()const{std::scoped_lock l(mutex_);std::uint64_t n=0;for(auto&[_,a]:assets_)n+=a.size;return n;}
void AssetStore::load(){std::scoped_lock l(mutex_);assets_.clear();std::ifstream in(metadata_path_);if(!in)return;std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;auto f=tabs(line);try{if(f.size()==7){AssetInfo a{.id=f[0],.owner_user_id=f[1],.name=unhex(f[2]),.mime_type=unhex(f[3]),.content_hash=f[4],.size=std::stoull(f[5]),.permissions=perm_all,.next_owner_permissions=perm_copy|perm_transfer,.created_unix=std::stoll(f[6])};assets_[a.id]=a;}else if(f.size()==9){AssetInfo a{.id=f[0],.owner_user_id=f[1],.name=unhex(f[2]),.mime_type=unhex(f[3]),.content_hash=f[4],.size=std::stoull(f[5]),.permissions=static_cast<PermissionMask>(std::stoul(f[6])),.next_owner_permissions=static_cast<PermissionMask>(std::stoul(f[7])),.created_unix=std::stoll(f[8])};assets_[a.id]=a;}}catch(...){}}}
void AssetStore::persist_locked()const{std::filesystem::path p(metadata_path_);if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());auto t=p.string()+".tmp";std::ofstream out(t,std::ios::trunc);if(!out)throw std::runtime_error("cannot write asset store");out<<"# OpenGenesisLINK assets v2\n";for(auto&[_,a]:assets_)out<<a.id<<'\t'<<a.owner_user_id<<'\t'<<hex(a.name)<<'\t'<<hex(a.mime_type)<<'\t'<<a.content_hash<<'\t'<<a.size<<'\t'<<a.permissions<<'\t'<<a.next_owner_permissions<<'\t'<<a.created_unix<<'\n';out.close();if(!out)throw std::runtime_error("cannot flush asset store");opengenesis::platform::replace_file(t,p);}
}
