#include "opengenesis/core/estate_store.hpp"
#include "opengenesis/platform/filesystem.hpp"
#include "opengenesis/security/crypto.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>

namespace opengenesis::core { namespace {
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
std::string clean(std::string v){for(char& c:v)if(c=='\t'||c=='\n'||c=='\r')c=' ';if(v.size()>96)v.resize(96);return v;}
std::vector<std::string> split(const std::string& s,char d){std::vector<std::string>o;std::size_t b=0;for(;;){auto e=s.find(d,b);o.push_back(s.substr(b,e==std::string::npos?e:e-b));if(e==std::string::npos)break;b=e+1;}return o;}
std::string join(const std::vector<std::string>& v,char d){std::string o;for(std::size_t i=0;i<v.size();++i){if(i)o+=d;o+=v[i];}return o;}
}
EstateStore::EstateStore(std::string path):path_(std::move(path)){load();}
std::optional<EstateInfo> EstateStore::create(std::string owner,std::string name,std::string& reason){name=clean(std::move(name));if(owner.empty()||name.empty()){reason="invalid-estate";return std::nullopt;}std::scoped_lock l(mutex_);EstateInfo e{.id=security::random_hex(16),.name=std::move(name),.owner_user_id=std::move(owner),.manager_user_ids={},.created_unix=now()};estates_[e.id]=e;persist_locked();reason.clear();return e;}
bool EstateStore::can_manage(std::string_view estate,std::string_view user)const{std::scoped_lock l(mutex_);auto it=estates_.find(std::string{estate});if(it==estates_.end())return false;return it->second.owner_user_id==user||std::find(it->second.manager_user_ids.begin(),it->second.manager_user_ids.end(),user)!=it->second.manager_user_ids.end();}
bool EstateStore::add_manager(std::string_view actor,std::string_view estate,std::string user,std::string& reason){std::scoped_lock l(mutex_);auto it=estates_.find(std::string{estate});if(it==estates_.end()){reason="estate-not-found";return false;}if(it->second.owner_user_id!=actor){reason="permission-denied";return false;}if(user.empty()){reason="invalid-user";return false;}if(std::find(it->second.manager_user_ids.begin(),it->second.manager_user_ids.end(),user)==it->second.manager_user_ids.end())it->second.manager_user_ids.push_back(std::move(user));persist_locked();reason.clear();return true;}
bool EstateStore::remove_manager(std::string_view actor,std::string_view estate,std::string_view user,std::string& reason){std::scoped_lock l(mutex_);auto it=estates_.find(std::string{estate});if(it==estates_.end()){reason="estate-not-found";return false;}if(it->second.owner_user_id!=actor){reason="permission-denied";return false;}std::erase(it->second.manager_user_ids,std::string{user});persist_locked();reason.clear();return true;}
bool EstateStore::attach_region(std::string_view actor,std::string_view estate,std::string region,std::string& reason){std::scoped_lock l(mutex_);auto it=estates_.find(std::string{estate});if(it==estates_.end()){reason="estate-not-found";return false;}if(it->second.owner_user_id!=actor&&std::find(it->second.manager_user_ids.begin(),it->second.manager_user_ids.end(),actor)==it->second.manager_user_ids.end()){reason="permission-denied";return false;}if(region.empty()){reason="invalid-region";return false;}auto& p=policies_[region];p.region_id=std::move(region);p.estate_id=std::string{estate};p.updated_unix=now();persist_locked();reason.clear();return true;}
bool EstateStore::update_region_policy(std::string_view actor,const RegionEstatePolicy& policy,std::string& reason){std::scoped_lock l(mutex_);auto eit=estates_.find(policy.estate_id);if(eit==estates_.end()){reason="estate-not-found";return false;}if(eit->second.owner_user_id!=actor&&std::find(eit->second.manager_user_ids.begin(),eit->second.manager_user_ids.end(),actor)==eit->second.manager_user_ids.end()){reason="permission-denied";return false;}auto pit=policies_.find(policy.region_id);if(pit==policies_.end()||pit->second.estate_id!=policy.estate_id){reason="region-not-attached";return false;}auto p=policy;p.max_agents=std::clamp<std::uint32_t>(p.max_agents,1,1000);p.maturity=std::min<std::uint8_t>(p.maturity,2);p.updated_unix=now();policies_[p.region_id]=p;persist_locked();reason.clear();return true;}
std::optional<EstateInfo> EstateStore::find(std::string_view id)const{std::scoped_lock l(mutex_);auto it=estates_.find(std::string{id});return it==estates_.end()?std::nullopt:std::optional<EstateInfo>{it->second};}
std::optional<RegionEstatePolicy> EstateStore::policy_for_region(std::string_view region)const{std::scoped_lock l(mutex_);auto it=policies_.find(std::string{region});return it==policies_.end()?std::nullopt:std::optional<RegionEstatePolicy>{it->second};}
std::vector<EstateInfo> EstateStore::list_for_user(std::string_view user)const{std::scoped_lock l(mutex_);std::vector<EstateInfo>o;for(auto&[_,e]:estates_)if(e.owner_user_id==user||std::find(e.manager_user_ids.begin(),e.manager_user_ids.end(),user)!=e.manager_user_ids.end())o.push_back(e);return o;}
std::vector<RegionEstatePolicy> EstateStore::regions_for_estate(std::string_view estate)const{std::scoped_lock l(mutex_);std::vector<RegionEstatePolicy>o;for(auto&[_,p]:policies_)if(p.estate_id==estate)o.push_back(p);return o;}
std::size_t EstateStore::count()const{std::scoped_lock l(mutex_);return estates_.size();}
void EstateStore::load(){std::scoped_lock l(mutex_);estates_.clear();policies_.clear();std::ifstream in(path_);std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;auto f=split(line,'\t');try{if(f.size()==6&&f[0]=="E"){EstateInfo e{.id=f[1],.name=f[2],.owner_user_id=f[3],.manager_user_ids=f[4].empty()?std::vector<std::string>{}:split(f[4],','),.created_unix=std::stoll(f[5])};estates_[e.id]=e;}else if(f.size()==13&&f[0]=="R"){RegionEstatePolicy p{.region_id=f[1],.estate_id=f[2],.public_access=f[3]=="1",.allow_fly=f[4]=="1",.allow_scripts=f[5]=="1",.allow_voice=f[6]=="1",.max_agents=static_cast<std::uint32_t>(std::stoul(f[7])),.maturity=static_cast<std::uint8_t>(std::stoul(f[8])),.landing_x=std::stod(f[9]),.landing_y=std::stod(f[10]),.landing_z=std::stod(f[11]),.updated_unix=std::stoll(f[12])};policies_[p.region_id]=p;}}catch(...){}}}
void EstateStore::persist_locked()const{std::filesystem::path p(path_);if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());auto t=p.string()+".tmp";std::ofstream out(t,std::ios::trunc);if(!out)throw std::runtime_error("cannot write estates");out<<"# OpenGenesisLINK estates v1\n";for(auto&[_,e]:estates_)out<<"E\t"<<e.id<<'\t'<<e.name<<'\t'<<e.owner_user_id<<'\t'<<join(e.manager_user_ids,',')<<'\t'<<e.created_unix<<'\n';for(auto&[_,r]:policies_)out<<"R\t"<<r.region_id<<'\t'<<r.estate_id<<'\t'<<(r.public_access?1:0)<<'\t'<<(r.allow_fly?1:0)<<'\t'<<(r.allow_scripts?1:0)<<'\t'<<(r.allow_voice?1:0)<<'\t'<<r.max_agents<<'\t'<<static_cast<unsigned>(r.maturity)<<'\t'<<r.landing_x<<'\t'<<r.landing_y<<'\t'<<r.landing_z<<'\t'<<r.updated_unix<<'\n';out.close();if(!out)throw std::runtime_error("cannot flush estates");opengenesis::platform::replace_file(t,p);}
}
