#include "opengenesis/core/group_store.hpp"
#include "opengenesis/platform/filesystem.hpp"
#include "opengenesis/security/crypto.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <vector>
namespace opengenesis::core { namespace {
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
std::string key(std::string_view g,std::string_view u){return std::string{g}+"|"+std::string{u};}
std::string hex(std::string_view v){constexpr char h[]="0123456789abcdef";std::string o(v.size()*2,'0');for(size_t i=0;i<v.size();++i){auto c=(unsigned char)v[i];o[i*2]=h[c>>4];o[i*2+1]=h[c&15];}return o;}
unsigned char nib(char c){if(c>='0'&&c<='9')return static_cast<unsigned char>(c-'0');if(c>='a'&&c<='f')return static_cast<unsigned char>(c-'a'+10);if(c>='A'&&c<='F')return static_cast<unsigned char>(c-'A'+10);throw std::runtime_error("hex");}
std::string unhex(std::string_view v){if(v.size()%2)throw std::runtime_error("hex");std::string o(v.size()/2,'\0');for(size_t i=0;i<o.size();++i)o[i]=(char)((nib(v[i*2])<<4)|nib(v[i*2+1]));return o;}
std::vector<std::string> tabs(const std::string& l){std::vector<std::string>f;size_t s=0;for(;;){auto e=l.find('\t',s);f.push_back(l.substr(s,e==std::string::npos?e:e-s));if(e==std::string::npos)break;s=e+1;}return f;}
bool valid_name(std::string_view s){return !s.empty()&&s.size()<=96&&std::none_of(s.begin(),s.end(),[](unsigned char c){return c<0x20||c==0x7f;});}
}
GroupStore::GroupStore(std::string path):path_(std::move(path)){load();}
std::uint32_t GroupStore::role_powers(std::string_view r){if(r=="owner")return group_power_all;if(r=="officer")return static_cast<std::uint32_t>(GroupPower::invite)|static_cast<std::uint32_t>(GroupPower::eject)|static_cast<std::uint32_t>(GroupPower::land)|static_cast<std::uint32_t>(GroupPower::objects)|static_cast<std::uint32_t>(GroupPower::chat)|static_cast<std::uint32_t>(GroupPower::notice);return static_cast<std::uint32_t>(GroupPower::chat);}
std::optional<GroupInfo> GroupStore::create(std::string founder,std::string name,std::string& reason){if(founder.empty()||!valid_name(name)){reason="invalid-group";return std::nullopt;}std::scoped_lock l(mutex_);for(auto&[_,g]:groups_)if(g.name==name){reason="group-name-exists";return std::nullopt;}GroupInfo g{.id=security::random_hex(16),.name=std::move(name),.founder_user_id=founder,.created_unix=now()};groups_[g.id]=g;const auto member_key=key(g.id,founder);members_[member_key]={.group_id=g.id,.user_id=std::move(founder),.role="owner",.powers=group_power_all,.joined_unix=g.created_unix};persist_locked();reason.clear();return g;}
std::optional<GroupMember> GroupStore::add_member(std::string_view actor,std::string_view gid,std::string user,std::string role,std::string& reason){if(user.empty()|| (role!="member"&&role!="officer")){reason="invalid-member";return std::nullopt;}std::scoped_lock l(mutex_);if(!groups_.contains(std::string{gid})){reason="group-not-found";return std::nullopt;}auto ait=members_.find(key(gid,actor));if(ait==members_.end()||(ait->second.powers&static_cast<std::uint32_t>(GroupPower::invite))==0){reason="permission-denied";return std::nullopt;}auto k=key(gid,user);if(members_.contains(k)){reason="already-member";return std::nullopt;}GroupMember m{.group_id=std::string{gid},.user_id=std::move(user),.role=std::move(role),.powers=role_powers(role),.joined_unix=now()};m.powers=role_powers(m.role);members_[k]=m;persist_locked();reason.clear();return m;}
bool GroupStore::remove_member(std::string_view actor,std::string_view gid,std::string_view user,std::string& reason){std::scoped_lock l(mutex_);auto target=members_.find(key(gid,user));if(target==members_.end()){reason="member-not-found";return false;}if(target->second.role=="owner"){reason="cannot-remove-owner";return false;}auto ait=members_.find(key(gid,actor));if(actor!=user&&(ait==members_.end()||(ait->second.powers&static_cast<std::uint32_t>(GroupPower::eject))==0)){reason="permission-denied";return false;}members_.erase(target);persist_locked();reason.clear();return true;}
bool GroupStore::set_role(std::string_view actor,std::string_view gid,std::string_view user,std::string role,std::string& reason){if(role!="member"&&role!="officer"){reason="invalid-role";return false;}std::scoped_lock l(mutex_);auto ait=members_.find(key(gid,actor));auto it=members_.find(key(gid,user));if(ait==members_.end()||it==members_.end()){reason="member-not-found";return false;}if((ait->second.powers&static_cast<std::uint32_t>(GroupPower::roles))==0||it->second.role=="owner"){reason="permission-denied";return false;}it->second.role=std::move(role);it->second.powers=role_powers(it->second.role);persist_locked();reason.clear();return true;}
bool GroupStore::is_member(std::string_view g,std::string_view u)const{std::scoped_lock l(mutex_);return members_.contains(key(g,u));}
bool GroupStore::has_power(std::string_view g,std::string_view u,GroupPower p)const{std::scoped_lock l(mutex_);auto it=members_.find(key(g,u));return it!=members_.end()&&(it->second.powers&static_cast<std::uint32_t>(p))!=0;}
std::optional<GroupInfo> GroupStore::find(std::string_view id)const{std::scoped_lock l(mutex_);auto it=groups_.find(std::string{id});return it==groups_.end()?std::nullopt:std::optional<GroupInfo>{it->second};}
std::vector<GroupInfo> GroupStore::list_for_user(std::string_view u)const{std::scoped_lock l(mutex_);std::vector<GroupInfo> r;for(auto&[_,m]:members_)if(m.user_id==u)if(auto it=groups_.find(m.group_id);it!=groups_.end())r.push_back(it->second);std::sort(r.begin(),r.end(),[](auto&a,auto&b){return a.name<b.name;});return r;}
std::vector<GroupMember> GroupStore::members(std::string_view g)const{std::scoped_lock l(mutex_);std::vector<GroupMember> r;for(auto&[_,m]:members_)if(m.group_id==g)r.push_back(m);std::sort(r.begin(),r.end(),[](auto&a,auto&b){return a.joined_unix<b.joined_unix;});return r;}
std::vector<std::string> GroupStore::group_ids_for_user(std::string_view u)const{std::scoped_lock l(mutex_);std::vector<std::string>r;for(auto&[_,m]:members_)if(m.user_id==u)r.push_back(m.group_id);std::sort(r.begin(),r.end());return r;}
std::size_t GroupStore::count()const{std::scoped_lock l(mutex_);return groups_.size();}
void GroupStore::load(){std::scoped_lock l(mutex_);groups_.clear();members_.clear();std::ifstream in(path_);if(!in)return;std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;auto f=tabs(line);try{if(f.size()==5&&f[0]=="G"){GroupInfo g{.id=f[1],.name=unhex(f[2]),.founder_user_id=f[3],.created_unix=std::stoll(f[4])};groups_[g.id]=g;}else if(f.size()==6&&f[0]=="M"){GroupMember m{.group_id=f[1],.user_id=f[2],.role=f[3],.powers=role_powers(f[3]),.joined_unix=std::stoll(f[5])};members_[key(m.group_id,m.user_id)]=m;}}catch(...){}}}
void GroupStore::persist_locked()const{std::filesystem::path p(path_);if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());auto t=p.string()+".tmp";std::ofstream out(t,std::ios::trunc);if(!out)throw std::runtime_error("cannot write groups");out<<"# OpenGenesisLINK groups v1\n";for(auto&[_,g]:groups_)out<<"G\t"<<g.id<<'\t'<<hex(g.name)<<'\t'<<g.founder_user_id<<'\t'<<g.created_unix<<'\n';for(auto&[_,m]:members_)out<<"M\t"<<m.group_id<<'\t'<<m.user_id<<'\t'<<m.role<<'\t'<<m.powers<<'\t'<<m.joined_unix<<'\n';out.close();if(!out)throw std::runtime_error("cannot flush groups");opengenesis::platform::replace_file(t,p);}
}
