#include "opengenesis/core/inventory_store.hpp"
#include "opengenesis/security/crypto.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <vector>
namespace opengenesis::core { namespace {
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
std::string hex(std::string_view v){constexpr char h[]="0123456789abcdef";std::string o(v.size()*2,'0');for(size_t i=0;i<v.size();++i){auto c=(unsigned char)v[i];o[i*2]=h[c>>4];o[i*2+1]=h[c&15];}return o;}
unsigned char nib(char c){if(c>='0'&&c<='9')return static_cast<unsigned char>(c-'0');if(c>='a'&&c<='f')return static_cast<unsigned char>(c-'a'+10);if(c>='A'&&c<='F')return static_cast<unsigned char>(c-'A'+10);throw std::runtime_error("hex");}
std::string unhex(std::string_view v){if(v.size()%2)throw std::runtime_error("hex");std::string o(v.size()/2,'\0');for(size_t i=0;i<o.size();++i)o[i]=(char)((nib(v[i*2])<<4)|nib(v[i*2+1]));return o;}
std::vector<std::string> tabs(const std::string& l){std::vector<std::string>f;size_t s=0;for(;;){auto e=l.find('\t',s);f.push_back(l.substr(s,e==std::string::npos?e:e-s));if(e==std::string::npos)break;s=e+1;}return f;}
bool valid_name(std::string_view v){return !v.empty()&&v.size()<=128&&std::none_of(v.begin(),v.end(),[](unsigned char c){return c<0x20||c==0x7f;});}
}
InventoryStore::InventoryStore(std::string path):path_(std::move(path)){load();}
InventoryFolder InventoryStore::ensure_root(std::string user){std::scoped_lock l(mutex_);if(auto it=root_by_user_.find(user);it!=root_by_user_.end())return folders_.at(it->second);InventoryFolder f{.id=security::random_hex(16),.owner_user_id=std::move(user),.parent_id={},.name="My Inventory",.created_unix=now()};root_by_user_[f.owner_user_id]=f.id;folders_[f.id]=f;persist_locked();return f;}
bool InventoryStore::folder_belongs_locked(std::string_view id,std::string_view user)const{auto it=folders_.find(std::string{id});return it!=folders_.end()&&it->second.owner_user_id==user;}
std::optional<InventoryFolder> InventoryStore::create_folder(std::string user,std::string parent,std::string name,std::string& reason){if(!valid_name(name)){reason="invalid-name";return std::nullopt;}std::scoped_lock l(mutex_);if(parent.empty()){auto it=root_by_user_.find(user);if(it==root_by_user_.end()){reason="missing-root";return std::nullopt;}parent=it->second;}if(!folder_belongs_locked(parent,user)){reason="invalid-parent";return std::nullopt;}InventoryFolder f{.id=security::random_hex(16),.owner_user_id=std::move(user),.parent_id=std::move(parent),.name=std::move(name),.created_unix=now()};folders_[f.id]=f;persist_locked();reason.clear();return f;}
std::optional<InventoryItem> InventoryStore::create_item(std::string user,std::string parent,std::string asset,std::string name,std::string& reason){if(asset.empty()){reason="invalid-asset";return std::nullopt;}if(!valid_name(name)){reason="invalid-name";return std::nullopt;}std::scoped_lock l(mutex_);if(parent.empty()){auto it=root_by_user_.find(user);if(it==root_by_user_.end()){reason="missing-root";return std::nullopt;}parent=it->second;}if(!folder_belongs_locked(parent,user)){reason="invalid-parent";return std::nullopt;}InventoryItem item{.id=security::random_hex(16),.owner_user_id=std::move(user),.parent_id=std::move(parent),.asset_id=std::move(asset),.name=std::move(name),.created_unix=now()};items_[item.id]=item;persist_locked();reason.clear();return item;}
UserInventory InventoryStore::list(std::string_view user){auto root=ensure_root(std::string{user});std::scoped_lock l(mutex_);UserInventory inv{.root=root, .folders={}, .items={}};for(auto&[_,f]:folders_)if(f.owner_user_id==user&&f.id!=root.id)inv.folders.push_back(f);for(auto&[_,i]:items_)if(i.owner_user_id==user)inv.items.push_back(i);std::sort(inv.folders.begin(),inv.folders.end(),[](auto&a,auto&b){return a.created_unix<b.created_unix;});std::sort(inv.items.begin(),inv.items.end(),[](auto&a,auto&b){return a.created_unix<b.created_unix;});return inv;}
std::size_t InventoryStore::folder_count()const{std::scoped_lock l(mutex_);return folders_.size();} std::size_t InventoryStore::item_count()const{std::scoped_lock l(mutex_);return items_.size();}
void InventoryStore::load(){std::scoped_lock l(mutex_);folders_.clear();items_.clear();root_by_user_.clear();std::ifstream in(path_);if(!in)return;std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;auto f=tabs(line);try{if(f.size()==6&&f[0]=="F"){InventoryFolder x{.id=f[1],.owner_user_id=f[2],.parent_id=f[3],.name=unhex(f[4]),.created_unix=std::stoll(f[5])};folders_[x.id]=x;if(x.parent_id.empty())root_by_user_[x.owner_user_id]=x.id;}else if(f.size()==7&&f[0]=="I"){InventoryItem x{.id=f[1],.owner_user_id=f[2],.parent_id=f[3],.asset_id=f[4],.name=unhex(f[5]),.created_unix=std::stoll(f[6])};items_[x.id]=x;}}catch(...){}}}
void InventoryStore::persist_locked()const{std::filesystem::path p(path_);if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());auto tmp=p.string()+".tmp";std::ofstream out(tmp,std::ios::trunc);if(!out)throw std::runtime_error("cannot write inventory");out<<"# OpenGenesisLINK inventory v1\n";for(auto&[_,f]:folders_)out<<"F\t"<<f.id<<'\t'<<f.owner_user_id<<'\t'<<f.parent_id<<'\t'<<hex(f.name)<<'\t'<<f.created_unix<<'\n';for(auto&[_,i]:items_)out<<"I\t"<<i.id<<'\t'<<i.owner_user_id<<'\t'<<i.parent_id<<'\t'<<i.asset_id<<'\t'<<hex(i.name)<<'\t'<<i.created_unix<<'\n';out.close();if(!out)throw std::runtime_error("cannot flush inventory");std::filesystem::rename(tmp,p);}
} // namespace opengenesis::core
