#include "opengenesis/core/region_registry.hpp"
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
namespace opengenesis::core {
RegionRegistry::RegionRegistry(std::string path):storage_path_(std::move(path)){load();}
bool RegionRegistry::register_region(RegionInfo r,std::string& reason){if(r.id.empty()||r.name.empty()||r.node_id.empty()){reason="invalid-region";return false;}std::scoped_lock lock(mutex_);for(const auto& [id,x]:regions_)if(id!=r.id&&x.grid_x==r.grid_x&&x.grid_y==r.grid_y){reason="grid-coordinate-in-use";return false;}if(const auto it=regions_.find(r.id);it!=regions_.end()&&it->second.node_id!=r.node_id){reason="region-owned-by-other-node";return false;}r.state="registered";regions_[r.id]=std::move(r);persist_locked();return true;}
bool RegionRegistry::valid_transition(const std::string& a,const std::string& b){if(a==b)return true;if(b=="error"||b=="offline")return true;return (a=="registered"&&b=="starting")||(a=="offline"&&b=="starting")||(a=="starting"&&b=="online")||(a=="online"&&b=="stopping")||(a=="stopping"&&b=="offline");}
bool RegionRegistry::update_state(const std::string& id,const std::string& node,const std::uint64_t gen,const std::string& state,std::string& reason){std::scoped_lock lock(mutex_);const auto it=regions_.find(id);if(it==regions_.end()){reason="unknown-region";return false;}if(it->second.node_id!=node||it->second.node_generation!=gen){reason="stale-or-foreign-session";return false;}if(!valid_transition(it->second.state,state)){reason="invalid-transition";return false;}it->second.state=state;persist_locked();return true;}
bool RegionRegistry::update_metrics(const RegionInfo& m,std::string& reason){std::scoped_lock lock(mutex_);const auto it=regions_.find(m.id);if(it==regions_.end()){reason="unknown-region";return false;}if(it->second.node_id!=m.node_id||it->second.node_generation!=m.node_generation){reason="stale-or-foreign-session";return false;}it->second.ticks=m.ticks;it->second.entities=m.entities;it->second.avatars=m.avatars;it->second.physics_bodies=m.physics_bodies;it->second.scene_events=m.scene_events;it->second.terrain_revision=m.terrain_revision;it->second.sim_fps=m.sim_fps;persist_locked();return true;}
void RegionRegistry::mark_node_offline(const std::string& node,const std::uint64_t gen){std::scoped_lock lock(mutex_);bool changed=false;for(auto& [_,r]:regions_)if(r.node_id==node&&r.node_generation==gen&&r.state!="offline"){r.state="offline";changed=true;}if(changed)persist_locked();}
std::optional<RegionInfo> RegionRegistry::find(const std::string& id)const{std::scoped_lock lock(mutex_);if(const auto it=regions_.find(id);it!=regions_.end())return it->second;return std::nullopt;}
std::vector<RegionInfo> RegionRegistry::list()const{std::scoped_lock lock(mutex_);std::vector<RegionInfo> out;out.reserve(regions_.size());for(const auto& [_,r]:regions_)out.push_back(r);return out;}
void RegionRegistry::load(){if(storage_path_.empty())return;std::ifstream in(storage_path_);std::string line;while(std::getline(in,line)){std::istringstream s(line);RegionInfo r;s>>std::quoted(r.id)>>std::quoted(r.name)>>std::quoted(r.node_id)>>std::quoted(r.state)>>r.grid_x>>r.grid_y>>r.node_generation>>r.ticks>>r.entities>>r.avatars>>r.physics_bodies>>r.sim_fps;if(s.good()){std::uint64_t events=0,terrain=0;if(s>>events>>terrain){r.scene_events=events;r.terrain_revision=terrain;}}if(!r.id.empty()){r.state="offline";regions_[r.id]=std::move(r);}}}
void RegionRegistry::persist_locked()const{if(storage_path_.empty())return;const std::filesystem::path p(storage_path_);if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());const auto tmp=storage_path_+".tmp";std::ofstream out(tmp,std::ios::trunc);for(const auto& [_,r]:regions_)out<<std::quoted(r.id)<<' '<<std::quoted(r.name)<<' '<<std::quoted(r.node_id)<<' '<<std::quoted(r.state)<<' '<<r.grid_x<<' '<<r.grid_y<<' '<<r.node_generation<<' '<<r.ticks<<' '<<r.entities<<' '<<r.avatars<<' '<<r.physics_bodies<<' '<<r.sim_fps<<' '<<r.scene_events<<' '<<r.terrain_revision<<'\n';out.close();std::filesystem::rename(tmp,storage_path_);}
}
